%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.23.0
-module(hex_pb_package).

-export([encode_msg/2, encode_msg/3]).
-export([decode_msg/2]).
-export([merge_msgs/3]).
-export([verify_msg/2]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([get_package_name/0]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).



encode_msg(Msg, MsgName) ->
    encode_msg(Msg, MsgName, []).


encode_msg(Msg, MsgName, _Opts) ->
    verify_msg(Msg, MsgName),
    case MsgName of
      'Dependency' -> e_msg_Dependency(Msg);
      'Release' -> e_msg_Release(Msg);
      'Package' -> e_msg_Package(Msg)
    end.


e_msg_Dependency(Msg) -> e_msg_Dependency(Msg, <<>>).


e_msg_Dependency(#{package := F1, requirement := F2} =
		     M,
		 Bin) ->
    B1 = begin
	   TrF1 = id(F1), e_type_string(TrF1, <<Bin/binary, 10>>)
	 end,
    B2 = begin
	   TrF2 = id(F2), e_type_string(TrF2, <<B1/binary, 18>>)
	 end,
    B3 = case M of
	   #{optional := F3} ->
	       TrF3 = id(F3), e_type_bool(TrF3, <<B2/binary, 24>>);
	   _ -> B2
	 end,
    case M of
      #{app := F4} ->
	  TrF4 = id(F4), e_type_string(TrF4, <<B3/binary, 34>>);
      _ -> B3
    end.

e_msg_Release(Msg) -> e_msg_Release(Msg, <<>>).


e_msg_Release(#{version := F1, checksum := F2,
		dependencies := F3},
	      Bin) ->
    B1 = begin
	   TrF1 = id(F1), e_type_string(TrF1, <<Bin/binary, 10>>)
	 end,
    B2 = begin
	   TrF2 = id(F2), e_type_bytes(TrF2, <<B1/binary, 18>>)
	 end,
    begin
      TrF3 = id(F3),
      if TrF3 == [] -> B2;
	 true -> e_field_Release_dependencies(TrF3, B2)
      end
    end.

e_msg_Package(Msg) -> e_msg_Package(Msg, <<>>).


e_msg_Package(#{releases := F1}, Bin) ->
    begin
      TrF1 = id(F1),
      if TrF1 == [] -> Bin;
	 true -> e_field_Package_releases(TrF1, Bin)
      end
    end.

e_mfield_Release_dependencies(Msg, Bin) ->
    SubBin = e_msg_Dependency(Msg, <<>>),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_field_Release_dependencies([Elem | Rest], Bin) ->
    Bin2 = <<Bin/binary, 26>>,
    Bin3 = e_mfield_Release_dependencies(id(Elem), Bin2),
    e_field_Release_dependencies(Rest, Bin3);
e_field_Release_dependencies([], Bin) -> Bin.

e_mfield_Package_releases(Msg, Bin) ->
    SubBin = e_msg_Release(Msg, <<>>),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_field_Package_releases([Elem | Rest], Bin) ->
    Bin2 = <<Bin/binary, 10>>,
    Bin3 = e_mfield_Package_releases(id(Elem), Bin2),
    e_field_Package_releases(Rest, Bin3);
e_field_Package_releases([], Bin) -> Bin.



e_type_bool(true, Bin) -> <<Bin/binary, 1>>;
e_type_bool(false, Bin) -> <<Bin/binary, 0>>.

e_type_string(S, Bin) ->
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.

e_type_bytes(Bytes, Bin) ->
    Bin2 = e_varint(byte_size(Bytes), Bin),
    <<Bin2/binary, Bytes/binary>>.

e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).



decode_msg(Bin, MsgName) when is_binary(Bin) ->
    case MsgName of
      'Dependency' -> d_msg_Dependency(Bin);
      'Release' -> d_msg_Release(Bin);
      'Package' -> d_msg_Package(Bin)
    end.



d_msg_Dependency(Bin) ->
    dfp_read_field_def_Dependency(Bin, 0, 0, id('$undef'),
				  id('$undef'), id('$undef'), id('$undef')).

dfp_read_field_def_Dependency(<<10, Rest/binary>>, Z1,
			      Z2, F1, F2, F3, F4) ->
    d_field_Dependency_package(Rest, Z1, Z2, F1, F2, F3,
			       F4);
dfp_read_field_def_Dependency(<<18, Rest/binary>>, Z1,
			      Z2, F1, F2, F3, F4) ->
    d_field_Dependency_requirement(Rest, Z1, Z2, F1, F2, F3,
				   F4);
dfp_read_field_def_Dependency(<<24, Rest/binary>>, Z1,
			      Z2, F1, F2, F3, F4) ->
    d_field_Dependency_optional(Rest, Z1, Z2, F1, F2, F3,
				F4);
dfp_read_field_def_Dependency(<<34, Rest/binary>>, Z1,
			      Z2, F1, F2, F3, F4) ->
    d_field_Dependency_app(Rest, Z1, Z2, F1, F2, F3, F4);
dfp_read_field_def_Dependency(<<>>, 0, 0, F1, F2, F3,
			      F4) ->
    S1 = #{package => F1, requirement => F2},
    S2 = if F3 == '$undef' -> S1;
	    true -> S1#{optional => F3}
	 end,
    if F4 == '$undef' -> S2;
       true -> S2#{app => F4}
    end;
dfp_read_field_def_Dependency(Other, Z1, Z2, F1, F2, F3,
			      F4) ->
    dg_read_field_def_Dependency(Other, Z1, Z2, F1, F2, F3,
				 F4).

dg_read_field_def_Dependency(<<1:1, X:7, Rest/binary>>,
			     N, Acc, F1, F2, F3, F4)
    when N < 32 - 7 ->
    dg_read_field_def_Dependency(Rest, N + 7, X bsl N + Acc,
				 F1, F2, F3, F4);
dg_read_field_def_Dependency(<<0:1, X:7, Rest/binary>>,
			     N, Acc, F1, F2, F3, F4) ->
    Key = X bsl N + Acc,
    case Key of
      10 ->
	  d_field_Dependency_package(Rest, 0, 0, F1, F2, F3, F4);
      18 ->
	  d_field_Dependency_requirement(Rest, 0, 0, F1, F2, F3,
					 F4);
      24 ->
	  d_field_Dependency_optional(Rest, 0, 0, F1, F2, F3, F4);
      34 ->
	  d_field_Dependency_app(Rest, 0, 0, F1, F2, F3, F4);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_Dependency(Rest, 0, 0, F1, F2, F3, F4);
	    1 -> skip_64_Dependency(Rest, 0, 0, F1, F2, F3, F4);
	    2 ->
		skip_length_delimited_Dependency(Rest, 0, 0, F1, F2, F3,
						 F4);
	    5 -> skip_32_Dependency(Rest, 0, 0, F1, F2, F3, F4)
	  end
    end;
dg_read_field_def_Dependency(<<>>, 0, 0, F1, F2, F3,
			     F4) ->
    S1 = #{package => F1, requirement => F2},
    S2 = if F3 == '$undef' -> S1;
	    true -> S1#{optional => F3}
	 end,
    if F4 == '$undef' -> S2;
       true -> S2#{app => F4}
    end.

d_field_Dependency_package(<<1:1, X:7, Rest/binary>>, N,
			   Acc, F1, F2, F3, F4)
    when N < 57 ->
    d_field_Dependency_package(Rest, N + 7, X bsl N + Acc,
			       F1, F2, F3, F4);
d_field_Dependency_package(<<0:1, X:7, Rest/binary>>, N,
			   Acc, _, F2, F3, F4) ->
    Len = X bsl N + Acc,
    <<Bytes:Len/binary, Rest2/binary>> = Rest,
    NewFValue = binary:copy(Bytes),
    dfp_read_field_def_Dependency(Rest2, 0, 0, NewFValue,
				  F2, F3, F4).


d_field_Dependency_requirement(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F1, F2, F3, F4)
    when N < 57 ->
    d_field_Dependency_requirement(Rest, N + 7,
				   X bsl N + Acc, F1, F2, F3, F4);
d_field_Dependency_requirement(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, F1, _, F3, F4) ->
    Len = X bsl N + Acc,
    <<Bytes:Len/binary, Rest2/binary>> = Rest,
    NewFValue = binary:copy(Bytes),
    dfp_read_field_def_Dependency(Rest2, 0, 0, F1,
				  NewFValue, F3, F4).


d_field_Dependency_optional(<<1:1, X:7, Rest/binary>>,
			    N, Acc, F1, F2, F3, F4)
    when N < 57 ->
    d_field_Dependency_optional(Rest, N + 7, X bsl N + Acc,
				F1, F2, F3, F4);
d_field_Dependency_optional(<<0:1, X:7, Rest/binary>>,
			    N, Acc, F1, F2, _, F4) ->
    NewFValue = X bsl N + Acc =/= 0,
    dfp_read_field_def_Dependency(Rest, 0, 0, F1, F2,
				  NewFValue, F4).


d_field_Dependency_app(<<1:1, X:7, Rest/binary>>, N,
		       Acc, F1, F2, F3, F4)
    when N < 57 ->
    d_field_Dependency_app(Rest, N + 7, X bsl N + Acc, F1,
			   F2, F3, F4);
d_field_Dependency_app(<<0:1, X:7, Rest/binary>>, N,
		       Acc, F1, F2, F3, _) ->
    Len = X bsl N + Acc,
    <<Bytes:Len/binary, Rest2/binary>> = Rest,
    NewFValue = binary:copy(Bytes),
    dfp_read_field_def_Dependency(Rest2, 0, 0, F1, F2, F3,
				  NewFValue).


skip_varint_Dependency(<<1:1, _:7, Rest/binary>>, Z1,
		       Z2, F1, F2, F3, F4) ->
    skip_varint_Dependency(Rest, Z1, Z2, F1, F2, F3, F4);
skip_varint_Dependency(<<0:1, _:7, Rest/binary>>, Z1,
		       Z2, F1, F2, F3, F4) ->
    dfp_read_field_def_Dependency(Rest, Z1, Z2, F1, F2, F3,
				  F4).


skip_length_delimited_Dependency(<<1:1, X:7,
				   Rest/binary>>,
				 N, Acc, F1, F2, F3, F4)
    when N < 57 ->
    skip_length_delimited_Dependency(Rest, N + 7,
				     X bsl N + Acc, F1, F2, F3, F4);
skip_length_delimited_Dependency(<<0:1, X:7,
				   Rest/binary>>,
				 N, Acc, F1, F2, F3, F4) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_Dependency(Rest2, 0, 0, F1, F2, F3,
				  F4).


skip_32_Dependency(<<_:32, Rest/binary>>, Z1, Z2, F1,
		   F2, F3, F4) ->
    dfp_read_field_def_Dependency(Rest, Z1, Z2, F1, F2, F3,
				  F4).


skip_64_Dependency(<<_:64, Rest/binary>>, Z1, Z2, F1,
		   F2, F3, F4) ->
    dfp_read_field_def_Dependency(Rest, Z1, Z2, F1, F2, F3,
				  F4).


d_msg_Release(Bin) ->
    dfp_read_field_def_Release(Bin, 0, 0, id('$undef'),
			       id('$undef'), id([])).

dfp_read_field_def_Release(<<10, Rest/binary>>, Z1, Z2,
			   F1, F2, F3) ->
    d_field_Release_version(Rest, Z1, Z2, F1, F2, F3);
dfp_read_field_def_Release(<<18, Rest/binary>>, Z1, Z2,
			   F1, F2, F3) ->
    d_field_Release_checksum(Rest, Z1, Z2, F1, F2, F3);
dfp_read_field_def_Release(<<26, Rest/binary>>, Z1, Z2,
			   F1, F2, F3) ->
    d_field_Release_dependencies(Rest, Z1, Z2, F1, F2, F3);
dfp_read_field_def_Release(<<>>, 0, 0, F1, F2, F3) ->
    #{version => F1, checksum => F2,
      dependencies => lists_reverse(F3)};
dfp_read_field_def_Release(Other, Z1, Z2, F1, F2, F3) ->
    dg_read_field_def_Release(Other, Z1, Z2, F1, F2, F3).

dg_read_field_def_Release(<<1:1, X:7, Rest/binary>>, N,
			  Acc, F1, F2, F3)
    when N < 32 - 7 ->
    dg_read_field_def_Release(Rest, N + 7, X bsl N + Acc,
			      F1, F2, F3);
dg_read_field_def_Release(<<0:1, X:7, Rest/binary>>, N,
			  Acc, F1, F2, F3) ->
    Key = X bsl N + Acc,
    case Key of
      10 -> d_field_Release_version(Rest, 0, 0, F1, F2, F3);
      18 -> d_field_Release_checksum(Rest, 0, 0, F1, F2, F3);
      26 ->
	  d_field_Release_dependencies(Rest, 0, 0, F1, F2, F3);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_Release(Rest, 0, 0, F1, F2, F3);
	    1 -> skip_64_Release(Rest, 0, 0, F1, F2, F3);
	    2 ->
		skip_length_delimited_Release(Rest, 0, 0, F1, F2, F3);
	    5 -> skip_32_Release(Rest, 0, 0, F1, F2, F3)
	  end
    end;
dg_read_field_def_Release(<<>>, 0, 0, F1, F2, F3) ->
    #{version => F1, checksum => F2,
      dependencies => lists_reverse(F3)}.

d_field_Release_version(<<1:1, X:7, Rest/binary>>, N,
			Acc, F1, F2, F3)
    when N < 57 ->
    d_field_Release_version(Rest, N + 7, X bsl N + Acc, F1,
			    F2, F3);
d_field_Release_version(<<0:1, X:7, Rest/binary>>, N,
			Acc, _, F2, F3) ->
    Len = X bsl N + Acc,
    <<Bytes:Len/binary, Rest2/binary>> = Rest,
    NewFValue = binary:copy(Bytes),
    dfp_read_field_def_Release(Rest2, 0, 0, NewFValue, F2,
			       F3).


d_field_Release_checksum(<<1:1, X:7, Rest/binary>>, N,
			 Acc, F1, F2, F3)
    when N < 57 ->
    d_field_Release_checksum(Rest, N + 7, X bsl N + Acc, F1,
			     F2, F3);
d_field_Release_checksum(<<0:1, X:7, Rest/binary>>, N,
			 Acc, F1, _, F3) ->
    Len = X bsl N + Acc,
    <<Bytes:Len/binary, Rest2/binary>> = Rest,
    NewFValue = binary:copy(Bytes),
    dfp_read_field_def_Release(Rest2, 0, 0, F1, NewFValue,
			       F3).


d_field_Release_dependencies(<<1:1, X:7, Rest/binary>>,
			     N, Acc, F1, F2, F3)
    when N < 57 ->
    d_field_Release_dependencies(Rest, N + 7, X bsl N + Acc,
				 F1, F2, F3);
d_field_Release_dependencies(<<0:1, X:7, Rest/binary>>,
			     N, Acc, F1, F2, F3) ->
    Len = X bsl N + Acc,
    <<Bs:Len/binary, Rest2/binary>> = Rest,
    NewFValue = id(d_msg_Dependency(Bs)),
    dfp_read_field_def_Release(Rest2, 0, 0, F1, F2,
			       cons(NewFValue, F3)).


skip_varint_Release(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		    F1, F2, F3) ->
    skip_varint_Release(Rest, Z1, Z2, F1, F2, F3);
skip_varint_Release(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		    F1, F2, F3) ->
    dfp_read_field_def_Release(Rest, Z1, Z2, F1, F2, F3).


skip_length_delimited_Release(<<1:1, X:7, Rest/binary>>,
			      N, Acc, F1, F2, F3)
    when N < 57 ->
    skip_length_delimited_Release(Rest, N + 7,
				  X bsl N + Acc, F1, F2, F3);
skip_length_delimited_Release(<<0:1, X:7, Rest/binary>>,
			      N, Acc, F1, F2, F3) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_Release(Rest2, 0, 0, F1, F2, F3).


skip_32_Release(<<_:32, Rest/binary>>, Z1, Z2, F1, F2,
		F3) ->
    dfp_read_field_def_Release(Rest, Z1, Z2, F1, F2, F3).


skip_64_Release(<<_:64, Rest/binary>>, Z1, Z2, F1, F2,
		F3) ->
    dfp_read_field_def_Release(Rest, Z1, Z2, F1, F2, F3).


d_msg_Package(Bin) ->
    dfp_read_field_def_Package(Bin, 0, 0, id([])).

dfp_read_field_def_Package(<<10, Rest/binary>>, Z1, Z2,
			   F1) ->
    d_field_Package_releases(Rest, Z1, Z2, F1);
dfp_read_field_def_Package(<<>>, 0, 0, F1) ->
    #{releases => lists_reverse(F1)};
dfp_read_field_def_Package(Other, Z1, Z2, F1) ->
    dg_read_field_def_Package(Other, Z1, Z2, F1).

dg_read_field_def_Package(<<1:1, X:7, Rest/binary>>, N,
			  Acc, F1)
    when N < 32 - 7 ->
    dg_read_field_def_Package(Rest, N + 7, X bsl N + Acc,
			      F1);
dg_read_field_def_Package(<<0:1, X:7, Rest/binary>>, N,
			  Acc, F1) ->
    Key = X bsl N + Acc,
    case Key of
      10 -> d_field_Package_releases(Rest, 0, 0, F1);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_Package(Rest, 0, 0, F1);
	    1 -> skip_64_Package(Rest, 0, 0, F1);
	    2 -> skip_length_delimited_Package(Rest, 0, 0, F1);
	    5 -> skip_32_Package(Rest, 0, 0, F1)
	  end
    end;
dg_read_field_def_Package(<<>>, 0, 0, F1) ->
    #{releases => lists_reverse(F1)}.

d_field_Package_releases(<<1:1, X:7, Rest/binary>>, N,
			 Acc, F1)
    when N < 57 ->
    d_field_Package_releases(Rest, N + 7, X bsl N + Acc,
			     F1);
d_field_Package_releases(<<0:1, X:7, Rest/binary>>, N,
			 Acc, F1) ->
    Len = X bsl N + Acc,
    <<Bs:Len/binary, Rest2/binary>> = Rest,
    NewFValue = id(d_msg_Release(Bs)),
    dfp_read_field_def_Package(Rest2, 0, 0,
			       cons(NewFValue, F1)).


skip_varint_Package(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		    F1) ->
    skip_varint_Package(Rest, Z1, Z2, F1);
skip_varint_Package(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		    F1) ->
    dfp_read_field_def_Package(Rest, Z1, Z2, F1).


skip_length_delimited_Package(<<1:1, X:7, Rest/binary>>,
			      N, Acc, F1)
    when N < 57 ->
    skip_length_delimited_Package(Rest, N + 7,
				  X bsl N + Acc, F1);
skip_length_delimited_Package(<<0:1, X:7, Rest/binary>>,
			      N, Acc, F1) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_Package(Rest2, 0, 0, F1).


skip_32_Package(<<_:32, Rest/binary>>, Z1, Z2, F1) ->
    dfp_read_field_def_Package(Rest, Z1, Z2, F1).


skip_64_Package(<<_:64, Rest/binary>>, Z1, Z2, F1) ->
    dfp_read_field_def_Package(Rest, Z1, Z2, F1).






merge_msgs(Prev, New, MsgName) ->
    case MsgName of
      'Dependency' -> merge_msg_Dependency(Prev, New);
      'Release' -> merge_msg_Release(Prev, New);
      'Package' -> merge_msg_Package(Prev, New)
    end.

merge_msg_Dependency(#{package := PFpackage,
		       requirement := PFrequirement} =
			 PMsg,
		     #{package := NFpackage, requirement := NFrequirement} =
			 NMsg) ->
    S1 = #{package =>
	       if NFpackage =:= undefined -> PFpackage;
		  true -> NFpackage
	       end,
	   requirement =>
	       if NFrequirement =:= undefined -> PFrequirement;
		  true -> NFrequirement
	       end},
    S2 = case {PMsg, NMsg} of
	   {_, #{optional := NFoptional}} ->
	       S1#{optional => NFoptional};
	   {#{optional := PFoptional}, _} ->
	       S1#{optional => PFoptional};
	   _ -> S1
	 end,
    case {PMsg, NMsg} of
      {_, #{app := NFapp}} -> S2#{app => NFapp};
      {#{app := PFapp}, _} -> S2#{app => PFapp};
      _ -> S2
    end.

merge_msg_Release(#{version := PFversion,
		    checksum := PFchecksum, dependencies := PFdependencies},
		  #{version := NFversion, checksum := NFchecksum,
		    dependencies := NFdependencies}) ->
    #{version =>
	  if NFversion =:= undefined -> PFversion;
	     true -> NFversion
	  end,
      checksum =>
	  if NFchecksum =:= undefined -> PFchecksum;
	     true -> NFchecksum
	  end,
      dependencies =>
	  'erlang_++'(PFdependencies, NFdependencies)}.

merge_msg_Package(#{releases := PFreleases},
		  #{releases := NFreleases}) ->
    #{releases => 'erlang_++'(PFreleases, NFreleases)}.



verify_msg(Msg, MsgName) ->
    case MsgName of
      'Dependency' -> v_msg_Dependency(Msg, ['Dependency']);
      'Release' -> v_msg_Release(Msg, ['Release']);
      'Package' -> v_msg_Package(Msg, ['Package']);
      _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


v_msg_Dependency(#{package := F1, requirement := F2} =
		     M,
		 Path) ->
    v_type_string(F1, [package | Path]),
    v_type_string(F2, [requirement | Path]),
    case M of
      #{optional := F3} -> v_type_bool(F3, [optional | Path]);
      _ -> ok
    end,
    case M of
      #{app := F4} -> v_type_string(F4, [app | Path]);
      _ -> ok
    end,
    ok;
v_msg_Dependency(M, Path) when is_map(M) ->
    mk_type_error({missing_fields,
		   [package, requirement] -- maps:keys(M), 'Dependency'},
		  M, Path);
v_msg_Dependency(X, Path) ->
    mk_type_error({expected_msg, 'Dependency'}, X, Path).

v_msg_Release(#{version := F1, checksum := F2,
		dependencies := F3},
	      Path) ->
    v_type_string(F1, [version | Path]),
    v_type_bytes(F2, [checksum | Path]),
    if is_list(F3) ->
	   _ = [v_msg_Dependency(Elem, [dependencies | Path])
		|| Elem <- F3],
	   ok;
       true ->
	   mk_type_error({invalid_list_of, {msg, 'Dependency'}},
			 F3, Path)
    end,
    ok;
v_msg_Release(M, Path) when is_map(M) ->
    mk_type_error({missing_fields,
		   [version, checksum, dependencies] -- maps:keys(M),
		   'Release'},
		  M, Path);
v_msg_Release(X, Path) ->
    mk_type_error({expected_msg, 'Release'}, X, Path).

v_msg_Package(#{releases := F1}, Path) ->
    if is_list(F1) ->
	   _ = [v_msg_Release(Elem, [releases | Path])
		|| Elem <- F1],
	   ok;
       true ->
	   mk_type_error({invalid_list_of, {msg, 'Release'}}, F1,
			 Path)
    end,
    ok;
v_msg_Package(M, Path) when is_map(M) ->
    mk_type_error({missing_fields,
		   [releases] -- maps:keys(M), 'Package'},
		  M, Path);
v_msg_Package(X, Path) ->
    mk_type_error({expected_msg, 'Package'}, X, Path).

v_type_bool(false, _Path) -> ok;
v_type_bool(true, _Path) -> ok;
v_type_bool(X, Path) ->
    mk_type_error(bad_boolean_value, X, Path).

v_type_string(S, Path) when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
      B when is_binary(B) -> ok;
      {error, _, _} ->
	  mk_type_error(bad_unicode_string, S, Path)
    catch
      error:badarg ->
	  mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path) ->
    mk_type_error(bad_unicode_string, X, Path).

v_type_bytes(B, _Path) when is_binary(B) -> ok;
v_type_bytes(X, Path) ->
    mk_type_error(bad_binary_value, X, Path).

-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error,
		  {Error, [{value, ValueSeen}, {path, Path2}]}}).


prettify_path([]) -> top_level;
prettify_path(PathR) ->
    list_to_atom(string:join(lists:map(fun atom_to_list/1,
				       lists:reverse(PathR)),
			     ".")).



-compile({nowarn_unused_function,id/1}).
-compile({inline,id/1}).
id(X) -> X.

-compile({nowarn_unused_function,cons/2}).
-compile({inline,cons/2}).
cons(Elem, Acc) -> [Elem | Acc].

-compile({nowarn_unused_function,lists_reverse/1}).
-compile({inline,lists_reverse/1}).
'lists_reverse'(L) -> lists:reverse(L).

-compile({nowarn_unused_function,'erlang_++'/2}).
-compile({inline,'erlang_++'/2}).
'erlang_++'(A, B) -> A ++ B.



get_msg_defs() ->
    [{{msg, 'Dependency'},
      [#{name => package, fnum => 1, rnum => 2,
	 type => string, occurrence => required, opts => []},
       #{name => requirement, fnum => 2, rnum => 3,
	 type => string, occurrence => required, opts => []},
       #{name => optional, fnum => 3, rnum => 4, type => bool,
	 occurrence => optional, opts => []},
       #{name => app, fnum => 4, rnum => 5, type => string,
	 occurrence => optional, opts => []}]},
     {{msg, 'Release'},
      [#{name => version, fnum => 1, rnum => 2,
	 type => string, occurrence => required, opts => []},
       #{name => checksum, fnum => 2, rnum => 3, type => bytes,
	 occurrence => required, opts => []},
       #{name => dependencies, fnum => 3, rnum => 4,
	 type => {msg, 'Dependency'}, occurrence => repeated,
	 opts => []}]},
     {{msg, 'Package'},
      [#{name => releases, fnum => 1, rnum => 2,
	 type => {msg, 'Release'}, occurrence => repeated,
	 opts => []}]}].


get_msg_names() -> ['Dependency', 'Release', 'Package'].


get_enum_names() -> [].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
      Fs when is_list(Fs) -> Fs;
      error -> erlang:error({no_such_msg, MsgName})
    end.


-spec fetch_enum_def(_) -> no_return().
fetch_enum_def(EnumName) ->
    erlang:error({no_such_enum, EnumName}).


find_msg_def('Dependency') ->
    [#{name => package, fnum => 1, rnum => 2,
       type => string, occurrence => required, opts => []},
     #{name => requirement, fnum => 2, rnum => 3,
       type => string, occurrence => required, opts => []},
     #{name => optional, fnum => 3, rnum => 4, type => bool,
       occurrence => optional, opts => []},
     #{name => app, fnum => 4, rnum => 5, type => string,
       occurrence => optional, opts => []}];
find_msg_def('Release') ->
    [#{name => version, fnum => 1, rnum => 2,
       type => string, occurrence => required, opts => []},
     #{name => checksum, fnum => 2, rnum => 3, type => bytes,
       occurrence => required, opts => []},
     #{name => dependencies, fnum => 3, rnum => 4,
       type => {msg, 'Dependency'}, occurrence => repeated,
       opts => []}];
find_msg_def('Package') ->
    [#{name => releases, fnum => 1, rnum => 2,
       type => {msg, 'Release'}, occurrence => repeated,
       opts => []}];
find_msg_def(_) -> error.


find_enum_def(_) -> error.


-spec enum_symbol_by_value(_, _) -> no_return().
enum_symbol_by_value(E, V) ->
    erlang:error({no_enum_defs, E, V}).


-spec enum_value_by_symbol(_, _) -> no_return().
enum_value_by_symbol(E, V) ->
    erlang:error({no_enum_defs, E, V}).



get_service_names() -> [].


get_service_def(_) -> error.


get_rpc_names(_) -> error.


find_rpc_def(_, _) -> error.



-spec fetch_rpc_def(_, _) -> no_return().
fetch_rpc_def(ServiceName, RpcName) ->
    erlang:error({no_such_rpc, ServiceName, RpcName}).


get_package_name() -> undefined.



gpb_version_as_string() ->
    "3.23.0".

gpb_version_as_list() ->
    [3,23,0].
